-- IB Məktəblər
insert into schools (name, district, edition, ib_programmes) values
('TISA — The International School of Azerbaijan', 'Nərimanov', 'ib', array['myp','dp']),
('European Azerbaijan School', 'Xətai', 'ib', array['myp','dp']),
('Baku Modern School', 'Nəsimi', 'ib', array['myp','dp']),
('QSI Baku International School', 'Nərimanov', 'ib', array['myp']),
('Dunya School', 'Binəqədi', 'ib', array['myp']),
('BIS — Baku International School', 'Nərimanov', 'ib', array['myp','dp']),
('Baku Oxford School', 'Yasamal', 'ib', array['myp']),
('İnternational Araz School', 'Xətai', 'ib', array['myp','dp']);

-- Bakı — Tam orta məktəblər (1-11)
insert into schools (name, district, edition) values
('Məktəb №1', 'Nəsimi', 'government'),
('Məktəb №2', 'Nəsimi', 'government'),
('Məktəb №3', 'Səbail', 'government'),
('Məktəb №4', 'Səbail', 'government'),
('Məktəb №5', 'Nəsimi', 'government'),
('Məktəb №6', 'Sabunçu', 'government'),
('Məktəb №7', 'Yasamal', 'government'),
('Məktəb №8', 'Nərimanov', 'government'),
('Məktəb №9', 'Yasamal', 'government'),
('Məktəb №10', 'Nəsimi', 'government'),
('Məktəb №11', 'Binəqədi', 'government'),
('Məktəb №12', 'Səbail', 'government'),
('Məktəb №13', 'Nərimanov', 'government'),
('Məktəb №14', 'Yasamal', 'government'),
('Məktəb №15', 'Nəsimi', 'government'),
('Məktəb №16', 'Xətai', 'government'),
('Məktəb №17', 'Yasamal', 'government'),
('Məktəb №18', 'Səbail', 'government'),
('Məktəb №19', 'Nəsimi', 'government'),
('Məktəb №20', 'Nərimanov', 'government'),
('Məktəb №21', 'Yasamal', 'government'),
('Məktəb №22', 'Nəsimi', 'government'),
('Məktəb №23', 'Suraxanı', 'government'),
('Məktəb №24', 'Xətai', 'government'),
('Məktəb №25', 'Yasamal', 'government'),
('Məktəb №26', 'Nərimanov', 'government'),
('Məktəb №27', 'Binəqədi', 'government'),
('Məktəb №28', 'Xətai', 'government'),
('Məktəb №29', 'Nəsimi', 'government'),
('Məktəb №30', 'Suraxanı', 'government'),
('Məktəb №31', 'Yasamal', 'government'),
('Məktəb №32', 'Nərimanov', 'government'),
('Məktəb №33', 'Xətai', 'government'),
('Məktəb №34', 'Binəqədi', 'government'),
('Məktəb №35', 'Səbail', 'government'),
('Məktəb №36', 'Nəsimi', 'government'),
('Məktəb №37', 'Yasamal', 'government'),
('Məktəb №38', 'Suraxanı', 'government'),
('Məktəb №39', 'Xətai', 'government'),
('Məktəb №40', 'Nərimanov', 'government'),
('Məktəb №41', 'Binəqədi', 'government'),
('Məktəb №42', 'Sabunçu', 'government'),
('Məktəb №43', 'Nəsimi', 'government'),
('Məktəb №44', 'Yasamal', 'government'),
('Məktəb №45', 'Xətai', 'government'),
('Məktəb №46', 'Nərimanov', 'government'),
('Məktəb №47', 'Suraxanı', 'government'),
('Məktəb №48', 'Binəqədi', 'government'),
('Məktəb №49', 'Sabunçu', 'government'),
('Məktəb №50', 'Nəsimi', 'government'),
('Məktəb №51', 'Xətai', 'government'),
('Məktəb №52', 'Nərimanov', 'government'),
('Məktəb №53', 'Yasamal', 'government'),
('Məktəb №54', 'Səbail', 'government'),
('Məktəb №55', 'Binəqədi', 'government'),
('Məktəb №56', 'Suraxanı', 'government'),
('Məktəb №57', 'Xətai', 'government'),
('Məktəb №58', 'Sabunçu', 'government'),
('Məktəb №59', 'Nərimanov', 'government'),
('Məktəb №60', 'Yasamal', 'government'),
('Məktəb №61', 'Nəsimi', 'government'),
('Məktəb №62', 'Xətai', 'government'),
('Məktəb №63', 'Sabunçu', 'government'),
('Məktəb №64', 'Suraxanı', 'government'),
('Məktəb №65', 'Binəqədi', 'government'),
('Məktəb №66', 'Nərimanov', 'government'),
('Məktəb №67', 'Yasamal', 'government'),
('Məktəb №68', 'Xətai', 'government'),
('Məktəb №69', 'Nəsimi', 'government'),
('Məktəb №70', 'Səbail', 'government'),
('Məktəb №71', 'Binəqədi', 'government'),
('Məktəb №72', 'Suraxanı', 'government'),
('Məktəb №73', 'Sabunçu', 'government'),
('Məktəb №74', 'Xətai', 'government'),
('Məktəb №75', 'Nərimanov', 'government'),
('Məktəb №76', 'Yasamal', 'government'),
('Məktəb №77', 'Nəsimi', 'government'),
('Məktəb №78', 'Suraxanı', 'government'),
('Məktəb №79', 'Binəqədi', 'government'),
('Məktəb №80', 'Sabunçu', 'government'),
('Məktəb №81', 'Xətai', 'government'),
('Məktəb №82', 'Nərimanov', 'government'),
('Məktəb №83', 'Yasamal', 'government'),
('Məktəb №84', 'Nəsimi', 'government'),
('Məktəb №85', 'Səbail', 'government'),
('Məktəb №86', 'Suraxanı', 'government'),
('Məktəb №87', 'Sabunçu', 'government'),
('Məktəb №88', 'Binəqədi', 'government'),
('Məktəb №89', 'Xətai', 'government'),
('Məktəb №90', 'Nərimanov', 'government'),
('Məktəb №91', 'Yasamal', 'government'),
('Məktəb №92', 'Nəsimi', 'government'),
('Məktəb №93', 'Suraxanı', 'government'),
('Məktəb №94', 'Sabunçu', 'government'),
('Məktəb №95', 'Binəqədi', 'government'),
('Məktəb №96', 'Xətai', 'government'),
('Məktəb №97', 'Nərimanov', 'government'),
('Məktəb №98', 'Yasamal', 'government'),
('Məktəb №99', 'Nəsimi', 'government'),
('Məktəb №100', 'Suraxanı', 'government'),
('Məktəb №101', 'Sabunçu', 'government'),
('Məktəb №102', 'Binəqədi', 'government'),
('Məktəb №103', 'Xətai', 'government'),
('Məktəb №104', 'Nərimanov', 'government'),
('Məktəb №105', 'Yasamal', 'government'),
('Məktəb №106', 'Nəsimi', 'government'),
('Məktəb №107', 'Sabunçu', 'government'),
('Məktəb №108', 'Suraxanı', 'government'),
('Məktəb №109', 'Binəqədi', 'government'),
('Məktəb №110', 'Xətai', 'government'),
('Məktəb №120', 'Sabunçu', 'government'),
('Məktəb №130', 'Suraxanı', 'government'),
('Məktəb №132', 'Binəqədi', 'government'),
('Məktəb №134', 'Binəqədi', 'government'),
('Məktəb №135', 'Nərimanov', 'government'),
('Məktəb №138', 'Xətai', 'government'),
('Məktəb №140', 'Yasamal', 'government'),
('Məktəb №141', 'Sabunçu', 'government'),
('Məktəb №142', 'Nəsimi', 'government'),
('Məktəb №145', 'Suraxanı', 'government'),
('Məktəb №148', 'Binəqədi', 'government'),
('Məktəb №150', 'Xətai', 'government'),
('Məktəb №152', 'Sabunçu', 'government'),
('Məktəb №153', 'Nərimanov', 'government'),
('Məktəb №155', 'Suraxanı', 'government'),
('Məktəb №158', 'Yasamal', 'government'),
('Məktəb №160', 'Binəqədi', 'government'),
('Məktəb №162', 'Xətai', 'government'),
('Məktəb №165', 'Nəsimi', 'government'),
('Məktəb №170', 'Sabunçu', 'government'),
('Məktəb №172', 'Suraxanı', 'government'),
('Məktəb №175', 'Binəqədi', 'government'),
('Məktəb №178', 'Xətai', 'government'),
('Məktəb №180', 'Nərimanov', 'government'),
('Məktəb №182', 'Yasamal', 'government'),
('Məktəb №185', 'Sabunçu', 'government'),
('Məktəb №188', 'Suraxanı', 'government'),
('Məktəb №190', 'Binəqədi', 'government'),
('Məktəb №192', 'Xətai', 'government'),
('Məktəb №195', 'Nərimanov', 'government'),
('Məktəb №198', 'Nəsimi', 'government'),
('Məktəb №200', 'Yasamal', 'government'),
('Məktəb №202', 'Sabunçu', 'government'),
('Məktəb №205', 'Suraxanı', 'government'),
('Məktəb №208', 'Binəqədi', 'government'),
('Məktəb №210', 'Xətai', 'government'),
('Məktəb №212', 'Nərimanov', 'government'),
('Məktəb №215', 'Yasamal', 'government'),
('Məktəb №220', 'Sabunçu', 'government'),
('Məktəb №225', 'Suraxanı', 'government'),
('Məktəb №230', 'Binəqədi', 'government'),
('Məktəb №235', 'Xətai', 'government'),
('Məktəb №240', 'Nərimanov', 'government'),
('Məktəb №245', 'Nəsimi', 'government'),
('Məktəb №250', 'Yasamal', 'government'),
('Məktəb №255', 'Sabunçu', 'government'),
('Məktəb №260', 'Suraxanı', 'government'),
('Məktəb №265', 'Binəqədi', 'government'),
('Məktəb №270', 'Xətai', 'government'),
('Məktəb №275', 'Nərimanov', 'government'),
('Məktəb №280', 'Sabunçu', 'government'),
('Məktəb №285', 'Suraxanı', 'government'),
('Məktəb №290', 'Binəqədi', 'government'),
('Məktəb №295', 'Xətai', 'government'),
('Məktəb №300', 'Yasamal', 'government'),
('Məktəb №305', 'Sabunçu', 'government'),
('Məktəb №310', 'Xəzər', 'government'),
('Məktəb №315', 'Suraxanı', 'government'),
('Məktəb №320', 'Binəqədi', 'government'),
('Məktəb №325', 'Xətai', 'government'),
('Məktəb №330', 'Sabunçu', 'government'),
('Məktəb №335', 'Nərimanov', 'government'),
('Məktəb №340', 'Suraxanı', 'government'),
('Məktəb №345', 'Binəqədi', 'government'),
('Məktəb №350', 'Xəzər', 'government'),
('Məktəb №355', 'Sabunçu', 'government'),
('Məktəb №360', 'Suraxanı', 'government'),
('Məktəb №365', 'Pirallahı', 'government'),
('Məktəb №370', 'Xəzər', 'government'),
('Məktəb №375', 'Sabunçu', 'government'),
('Məktəb №380', 'Suraxanı', 'government'),
('Məktəb №385', 'Qaradağ', 'government'),
('Məktəb №390', 'Qaradağ', 'government'),
('Məktəb №395', 'Xəzər', 'government'),
('Məktəb №400', 'Sabunçu', 'government');

-- Bakı — Lisey və Gimnaziyalar
insert into schools (name, district, edition) values
('Bakı Avropa Liseyi', 'Nəsimi', 'government'),
('Heydər Əliyev adına Lisey', 'Yasamal', 'government'),
('Bakı Slavyan Liseyi', 'Nəsimi', 'government'),
('Təhsil Nazirliyi Liseyi', 'Nərimanov', 'government'),
('Fizika-Riyaziyyat-İnformatika Liseyi', 'Yasamal', 'government'),
('Humanitar fənlər Liseyi', 'Nəsimi', 'government'),
('Bakı Gimnaziyası', 'Səbail', 'government'),
('Klassik Gimnaziya', 'Yasamal', 'government'),
('Zərdabi adına Lisey', 'Binəqədi', 'government'),
('Tusi adına Lisey', 'Yasamal', 'government'),
('Akademik Lisey', 'Nərimanov', 'government'),
('Texniki Lisey', 'Xətai', 'government');

-- Bakı — Xüsusi və Özəl məktəblər
insert into schools (name, district, edition) values
('Dunya School', 'Binəqədi', 'government'),
('Tusi School', 'Yasamal', 'government'),
('Kaspi Liseyi', 'Nəsimi', 'government'),
('Modern Təhsil Kompleksi', 'Xətai', 'government'),
('Intellect School', 'Nərimanov', 'government'),
('XXI Əsr Təhsil Mərkəzi', 'Yasamal', 'government'),
('Star School', 'Binəqədi', 'government'),
('Progress School', 'Xətai', 'government'),
('Nurlar Təhsil Mərkəzi', 'Sabunçu', 'government'),
('Yeni Təhsil Kompleksi', 'Suraxanı', 'government');

-- Regionlar — Gəncə
insert into schools (name, district, edition) values
('Gəncə şəhər Məktəb №1', 'Gəncə', 'government'),
('Gəncə şəhər Məktəb №2', 'Gəncə', 'government'),
('Gəncə şəhər Məktəb №3', 'Gəncə', 'government'),
('Gəncə şəhər Məktəb №5', 'Gəncə', 'government'),
('Gəncə şəhər Məktəb №7', 'Gəncə', 'government'),
('Gəncə şəhər Məktəb №10', 'Gəncə', 'government'),
('Gəncə şəhər Məktəb №15', 'Gəncə', 'government'),
('Gəncə şəhər Məktəb №20', 'Gəncə', 'government'),
('Gəncə şəhər Məktəb №25', 'Gəncə', 'government'),
('Gəncə şəhər Məktəb №30', 'Gəncə', 'government'),
('Gəncə şəhər Məktəb №35', 'Gəncə', 'government'),
('Gəncə şəhər Lisey', 'Gəncə', 'government');

-- Regionlar — Sumqayıt
insert into schools (name, district, edition) values
('Sumqayıt şəhər Məktəb №1', 'Sumqayıt', 'government'),
('Sumqayıt şəhər Məktəb №2', 'Sumqayıt', 'government'),
('Sumqayıt şəhər Məktəb №3', 'Sumqayıt', 'government'),
('Sumqayıt şəhər Məktəb №5', 'Sumqayıt', 'government'),
('Sumqayıt şəhər Məktəb №7', 'Sumqayıt', 'government'),
('Sumqayıt şəhər Məktəb №10', 'Sumqayıt', 'government'),
('Sumqayıt şəhər Məktəb №15', 'Sumqayıt', 'government'),
('Sumqayıt şəhər Məktəb №20', 'Sumqayıt', 'government'),
('Sumqayıt şəhər Məktəb №25', 'Sumqayıt', 'government'),
('Sumqayıt şəhər Məktəb №30', 'Sumqayıt', 'government'),
('Sumqayıt şəhər Məktəb №35', 'Sumqayıt', 'government'),
('Sumqayıt şəhər Məktəb №40', 'Sumqayıt', 'government'),
('Sumqayıt şəhər Lisey', 'Sumqayıt', 'government');

-- Regionlar — Mingəçevir
insert into schools (name, district, edition) values
('Mingəçevir şəhər Məktəb №1', 'Mingəçevir', 'government'),
('Mingəçevir şəhər Məktəb №2', 'Mingəçevir', 'government'),
('Mingəçevir şəhər Məktəb №3', 'Mingəçevir', 'government'),
('Mingəçevir şəhər Məktəb №5', 'Mingəçevir', 'government'),
('Mingəçevir şəhər Məktəb №7', 'Mingəçevir', 'government'),
('Mingəçevir şəhər Məktəb №10', 'Mingəçevir', 'government');

-- Regionlar — Lənkəran
insert into schools (name, district, edition) values
('Lənkəran şəhər Məktəb №1', 'Lənkəran', 'government'),
('Lənkəran şəhər Məktəb №2', 'Lənkəran', 'government'),
('Lənkəran şəhər Məktəb №3', 'Lənkəran', 'government'),
('Lənkəran şəhər Məktəb №5', 'Lənkəran', 'government'),
('Lənkəran şəhər Məktəb №7', 'Lənkəran', 'government'),
('Lənkəran şəhər Məktəb №10', 'Lənkəran', 'government');

-- Regionlar — Şəki
insert into schools (name, district, edition) values
('Şəki şəhər Məktəb №1', 'Şəki', 'government'),
('Şəki şəhər Məktəb №2', 'Şəki', 'government'),
('Şəki şəhər Məktəb №3', 'Şəki', 'government'),
('Şəki şəhər Məktəb №5', 'Şəki', 'government'),
('Şəki şəhər Məktəb №7', 'Şəki', 'government');

-- Regionlar — Şirvan
insert into schools (name, district, edition) values
('Şirvan şəhər Məktəb №1', 'Şirvan', 'government'),
('Şirvan şəhər Məktəb №2', 'Şirvan', 'government'),
('Şirvan şəhər Məktəb №3', 'Şirvan', 'government'),
('Şirvan şəhər Məktəb №5', 'Şirvan', 'government');

-- Regionlar — Naxçıvan
insert into schools (name, district, edition) values
('Naxçıvan şəhər Məktəb №1', 'Naxçıvan', 'government'),
('Naxçıvan şəhər Məktəb №2', 'Naxçıvan', 'government'),
('Naxçıvan şəhər Məktəb №3', 'Naxçıvan', 'government'),
('Naxçıvan şəhər Məktəb №5', 'Naxçıvan', 'government'),
('Naxçıvan şəhər Məktəb №7', 'Naxçıvan', 'government'),
('Naxçıvan şəhər Lisey', 'Naxçıvan', 'government');

-- Regionlar — Digər rayonlar
insert into schools (name, district, edition) values
('Quba rayon Məktəb №1', 'Quba', 'government'),
('Quba rayon Məktəb №2', 'Quba', 'government'),
('Qusar rayon Məktəb №1', 'Qusar', 'government'),
('Xaçmaz rayon Məktəb №1', 'Xaçmaz', 'government'),
('İsmayıllı rayon Məktəb №1', 'İsmayıllı', 'government'),
('Şamaxı rayon Məktəb №1', 'Şamaxı', 'government'),
('Qəbələ rayon Məktəb №1', 'Qəbələ', 'government'),
('Oğuz rayon Məktəb №1', 'Oğuz', 'government'),
('Balakən rayon Məktəb №1', 'Balakən', 'government'),
('Zaqatala rayon Məktəb №1', 'Zaqatala', 'government'),
('Bərdə rayon Məktəb №1', 'Bərdə', 'government'),
('Ağdam rayon Məktəb №1', 'Ağdam', 'government'),
('Ağdaş rayon Məktəb №1', 'Ağdaş', 'government'),
('Göyçay rayon Məktəb №1', 'Göyçay', 'government'),
('Kürdəmir rayon Məktəb №1', 'Kürdəmir', 'government'),
('Sabirabad rayon Məktəb №1', 'Sabirabad', 'government'),
('Salyan rayon Məktəb №1', 'Salyan', 'government'),
('Neftçala rayon Məktəb №1', 'Neftçala', 'government'),
('Biləsuvar rayon Məktəb №1', 'Biləsuvar', 'government'),
('Masallı rayon Məktəb №1', 'Masallı', 'government'),
('Lerik rayon Məktəb №1', 'Lerik', 'government'),
('Astara rayon Məktəb №1', 'Astara', 'government'),
('Yardımlı rayon Məktəb №1', 'Yardımlı', 'government'),
('Cəlilabad rayon Məktəb №1', 'Cəlilabad', 'government'),
('Tovuz rayon Məktəb №1', 'Tovuz', 'government'),
('Qazax rayon Məktəb №1', 'Qazax', 'government'),
('Ağstafa rayon Məktəb №1', 'Ağstafa', 'government'),
('Şəmkir rayon Məktəb №1', 'Şəmkir', 'government'),
('Göygöl rayon Məktəb №1', 'Göygöl', 'government'),
('Samux rayon Məktəb №1', 'Samux', 'government'),
('Daşkəsən rayon Məktəb №1', 'Daşkəsən', 'government'),
('Gədəbəy rayon Məktəb №1', 'Gədəbəy', 'government'),
('Füzuli rayon Məktəb №1', 'Füzuli', 'government'),
('Cəbrayıl rayon Məktəb №1', 'Cəbrayıl', 'government'),
('Zəngilan rayon Məktəb №1', 'Zəngilan', 'government'),
('Qubadlı rayon Məktəb №1', 'Qubadlı', 'government'),
('Laçın rayon Məktəb №1', 'Laçın', 'government'),
('Kəlbəcər rayon Məktəb №1', 'Kəlbəcər', 'government'),
('Şuşa şəhər Məktəb №1', 'Şuşa', 'government'),
('Xankəndi şəhər Məktəb №1', 'Xankəndi', 'government'),
('Xocalı rayon Məktəb №1', 'Xocalı', 'government'),
('Ağcabədi rayon Məktəb №1', 'Ağcabədi', 'government'),
('Beyləqan rayon Məktəb №1', 'Beyləqan', 'government'),
('İmişli rayon Məktəb №1', 'İmişli', 'government'),
('Hacıqabul rayon Məktəb №1', 'Hacıqabul', 'government'),
('Abşeron rayon Məktəb №1', 'Abşeron', 'government'),
('Abşeron rayon Məktəb №2', 'Abşeron', 'government'),
('Abşeron rayon Məktəb №3', 'Abşeron', 'government'),
('Xızı rayon Məktəb №1', 'Xızı', 'government'),
('Siyəzən rayon Məktəb №1', 'Siyəzən', 'government'),
('Şabran rayon Məktəb №1', 'Şabran', 'government'),
('Yevlax şəhər Məktəb №1', 'Yevlax', 'government'),
('Yevlax şəhər Məktəb №2', 'Yevlax', 'government'),
('Zərdab rayon Məktəb №1', 'Zərdab', 'government'),
('Ucar rayon Məktəb №1', 'Ucar', 'government');
